name: Build Backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install requirements
        run: pip3 install -r ./backend/requirements.txt

      - name: Run all the tests
        run: cd ./backend; python3 -m pytest
        env:
          DATABASE_URL: sqlite:///./tests/test.db

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Buildx with all platforms
        run: docker buildx build --tag rangerdigital/sakuta:latest --platform linux/amd64 --output type=registry backend/.
